variables:
  REGISTRY_HOST: pensotec.com:5005

build:
  stage: build
  image: docker:18-git
  services:
    - docker:18-dind
  variables:
    DOCKER_HOST: tcp://localhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $REGISTRY_HOST
    - cd GatewayApi
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$CI_COMMIT_SHA -t $REGISTRY_HOST/$CI_PROJECT_PATH:api-gw-test .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:api-gw-test

